name: GNU

on: [push, pull_request]

jobs:
  gnu:
    name: Run GNU tests
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
    - name: Checkout code uutil
      uses: actions/checkout@v2
      with:
        path: 'uutils'
    - name: Chechout GNU coreutils
      uses: actions/checkout@v2
      with:
        repository: 'coreutils/coreutils'
        path: 'gnu'
    - name: Chechout GNU corelib
      uses: actions/checkout@v2
      with:
        repository: 'coreutils/gnulib'
        path: 'gnulib'
        fetch-depth: 0 # gnu gets upset if gnulib is a shallow checkout
    - name: Install `rust` toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        profile: minimal # minimal component installation (ie, no documentation)
        components: rustfmt
    - name: Build binaries
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install autoconf autopoint bison texinfo gperf gcc g++ gdb python-pyinotify expect python3-sphinx
        pushd uutils
        make PROFILE=release
        BUILDDIR="$PWD/target/release/"
        popd
        GNULIB_SRCDIR="$PWD/gnulib"
        pushd gnu/
        ./bootstrap --gnulib-srcdir="$GNULIB_SRCDIR"
        ./configure --quiet --disable-gcc-warnings
        # Change the PATH in the Makefile to test the uutils coreutils instead of the GNU coreutils 
        sed -i "s/^[[:blank:]]*PATH=.*/  PATH='${BUILDDIR//\//\\/}\$(PATH_SEPARATOR)'\"\$\$PATH\" \\\/" Makefile
        sed -i 's| tr | /usr/bin/tr |' tests/init.sh
        make
        # Generate the factor tests, so they can be fixed
        for i in $(seq -w 1 36)
        do
          make tests/factor/t${i}.sh
        done
        grep -rl 'path_prepend_' tests/* | xargs sed -i 's|path_prepend_ ./src||'
        sed -i -e 's|^seq |/usr/bin/seq |' tests/factor/t*sh
        sed -i -e '/tests\/misc\/cat-self.sh/ D' Makefile # issue #1707
        sed -i -e '/tests\/misc\/numfmt.pl/ D' Makefile # issue #1708
        sed -i -e '/tests\/chown\/preserve-root.sh/ D' Makefile # issue #1709
        sed -i -e '/tests\/cp\/existing-perm-race.sh/ D' Makefile # cp doesn't implement copy-contents
        # Remove tests that rely on seq with large numbers. See issue #1703
        sed -i -e '/tests\/misc\/seq.pl/ D' \
               -e '/tests\/misc\/seq-precision.sh/D' \
               Makefile
        test -f "${BUILDDIR}/getlimits" || cp src/getlimits "${BUILDDIR}"
    - name: Run GNU tests
      shell: bash
      run: |
        BUILDDIR="${PWD}/uutils/target/release"
        GNULIB_DIR="${PWD}/gnulib"
        pushd gnu
        timeout -sKILL 3600 make check SUBDIRS=. RUN_EXPENSIVE_TESTS=yes RUN_VERY_EXPENSIVE_TESTS=yes VERBOSE=no || : # Have timeout send SIGKILL so make can't delete the log of the test that was in progress when timeout fired
    - uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: gnu/tests/**/*.log
